paths:
  local_history: ~/.zsh_history
  remote_history: ~/.zsh_history_git/history.txt
  git_repo: ~/.zsh_history_git
  log_file: ~/.history_syncer/history_syncer.log
  pid_file: ~/.history_syncer/history_syncer.pid

settings:
  sync_interval_seconds: 3600
  sync_type: ssh

git:
  repository_url: git@github.com:DmitrievSS/zsh_history.git
  branch: main
  remote_name: origin

ssh:
  host: ssd-test.sas.yp-c.yandex.net
  port: 22
  username: ssdmitriev
  remote_path: ~/.zsh_history
  lock_file: zsh_sync_lock.lock 