#!/bin/bash

# Получаем абсолютный путь к директории скрипта
SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

# Активируем виртуальное окружение и запускаем скрипт
source "$SCRIPT_DIR/venv/bin/activate"
python "$SCRIPT_DIR/history_syncer.py" "$@" 